### ISSUE TITLE
mocking node built ins e.g. fs

### ISSUE THREAD

**Issue by cabbiepete** [deepsweet/mocku#4]
I have a module with 

```
import fs from 'fs';

export default function moduleFunc() {
  const manifest = JSON.parse(fs.readFileSync('somepath', 'utf-8'));
  return manifest
}
```

If I try to mock the fs call like this:

```
fs = {
    readFileSync: expectation.create('readFileSync')
}
mock(modulePath, {fs})
    
    import(modulePath)
      .then((mod) => {
        moduleFunc = mod.default;
        return done();
      })
```

I get a warning as below when I attempt to run the test

```
SyntaxError: Missing export name 'default' in ES module: fs
```

Maybe because `fs` is not a es6 module?
Am I approaching this incorrectly?

**Comment by deepsweet** [comment]
Damn, somehow I wasn't watching this particular repo and missed your issue for the second time. Sorry for that, already fixed :)

Regarding the `fs` mocking – your example looks correct for me, actually I'm doing quite the same a lot, for example [here](https://github.com/deepsweet/dleet/blob/master/test/index.ts). Are you using `mocku@0.2.1`?

**Comment by deepsweet** [comment]
I got it. That's because you have imported `fs` as `import fs from 'fs'` which from ESM point of view means that `fs` contains a `default` export. It will work if you change it to `import { readFileSync } from 'fs'` or change the mock to `fs: { default: { ... } }`.

Going to think about this more, maybe it's related to explicit `__esModule: true` in `mocku` itself, please ping if it still doesn't work for you.

**Comment by cabbiepete** [comment]
@deepsweet I have a more basic example working using this approach so pretty sure this solves the issue. Thanks for the update.

**Comment by cabbiepete** [comment]
For anyone else finding this issue in future, the working simple example can be seen in a mocku example tests repo I started and will add to version as at today:

https://github.com/cabbiepete/mocku-test/blob/8c9275d3c34002f9cb0ec183735fea929af88546/test/lib/manifest.js
